version: 2

project_name: glcli

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - id: glcli
    main: ./cmd/glcli/
    binary: glcli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - README.md
      - LICENSE
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^feat"
      order: 0
    - title: "Bug Fixes"
      regexp: "^fix"
      order: 1
    - title: "Other"
      order: 999

release:
  github:
    owner: bearlogin
    name: gitlab-awesome-cli
  name_template: "v{{ .Version }}"
  draft: false
  prerelease: auto
  footer: |
    ## Installation

    ```bash
    # go install
    go install github.com/bearlogin/gitlab-awesome-cli/cmd/glcli@{{ .Tag }}

    # or download a binary above and place it in your PATH
    ```
